    //
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.22 at 07:12:59 PM BST 
//
package eu.arrowhead.core.qos.monitor.event.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Event complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Event"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.arrowhead.org/eventhandler/events}Metadata"/&gt;
 *         &lt;element name="payload" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "from",
    "type",
    "description",
    "payload"
})

@XmlRootElement(name = "event")
public class Event {

    /**
     * Variable containing the event's producer uid.
     */
    @XmlElement(required = true)
    protected String from;

    /**
     * Variable containing the event type.
     */
    @XmlElement(required = true)
    protected String type;

    /**
     * Variable containing the event's metadata.
     */
    @XmlElement(required = true)
    protected Metadata description;

    /**
     * Variable containing the event payload.
     */
    @XmlElement(required = true)
    protected String payload;

    /**
     * Gets the value of the from property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link Metadata }
     *
     */
    public Metadata getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link Metadata }
     *
     */
    public void setDescription(Metadata value) {
        this.description = value;
    }

    /**
     * Gets the value of the payload property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPayload(String value) {
        this.payload = value;
    }

}
